run_fast_tests:
  image: python:3.6
  stage: test

  script:
    - apt-get update
    - apt-get --yes install git
    - export GIT_SSL_NO_VERIFY=1
    - pip install Cython
    - cd ${CI_PROJECT_DIR}
    - pip install --upgrade pip setuptools
    - pip install tensorflow==1.15
    - pip install .
    - pip install -U pytest
    - pytest -s -v -m "not slow"
  tags: [docker]
